"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env (never committed). Everything env-driven so live data
# is a config swap, never a code change.
load_dotenv(BASE_DIR / '.env')


def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-jl$d!=0w9v++2x&_zl$i#q$!*a^lc2-7w-!4^1p19uv5=j+qlb',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    # Customer 360
    'c360',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static (admin / DRF browsable-API CSS) straight
    # from the app process under gunicorn, so the container needs no static server.
    # Must sit immediately after SecurityMiddleware (WhiteNoise docs).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# App DB — Customer 360's own tables (users/OTP/recommendation feedback/JWT
# blacklist). NOT the analytics warehouse (that's Trino, see C360['trino_config']).
# SQLite by default so the app runs with zero setup and tests stay in-memory; set
# DB_ENGINE=django.db.backends.postgresql + DB_* in the deploy env to run on the
# same Postgres server the portfolio uses. A containerised SQLite file must be
# bind-mounted (see deploy/DEPLOY.md) or it is lost when the container is replaced.
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
    }
}
for _key in ('USER', 'PASSWORD', 'HOST', 'PORT'):
    _val = os.environ.get(f'DB_{_key}')
    if _val:
        DATABASES['default'][_key] = _val
if DATABASES['default']['ENGINE'] != 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('CONN_MAX_AGE', 60)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic writes here in the Docker build; WhiteNoise serves it at runtime.
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Compress without manifest-hashing — avoids strict "missing file" errors from
# third-party apps' static; WhiteNoise serves the compressed result.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # JWT is the app's auth (the SPA sends a Bearer access token). ClaimsJWTAuthentication
    # is JWTAuthentication that also accepts tokens minted by the HF portfolio backend
    # (single sign-on): it builds the acting user from the token's identity + RBAC claims
    # with no shared user database — see c360/auth/claims.py. SessionAuth stays only for
    # the browsable API / Django admin during local dev.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'c360.auth.claims.ClaimsJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Permissive by default in local dev so the documented header-driven RBAC seam
    # still works; flip C360_REQUIRE_AUTH=true (below) to require a token in prod.
    # RBAC scoping is enforced in the warehouse/rbac layer regardless of the DRF
    # permission class so it cannot be bypassed from the UI. See c360/rbac/scoping.py.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'EXCEPTION_HANDLER': 'c360.api.errors.exception_handler',
}

# ---------------------------------------------------------------------------
# Simple JWT — mirrors the HF Group backend. Short-lived access token the SPA
# silently refreshes on 401; rotation + blacklist shrink a leaked token's window.
# ---------------------------------------------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('ACCESS_TOKEN_LIFETIME_MINUTES', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('REFRESH_TOKEN_LIFETIME_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    # Single sign-on with the HF portfolio backend: HS256 verifies with the signing
    # key, so pointing C360_JWT_SIGNING_KEY at the portfolio's SECRET_KEY (in both
    # environments) makes a portfolio-issued token validate here. Defaults to this
    # app's own SECRET_KEY for standalone/local runs. This is a *token* trust key,
    # deliberately separate from Django's SECRET_KEY (which also signs sessions, the
    # MFA ticket and password-reset codes) so SSO doesn't widen those surfaces.
    'SIGNING_KEY': os.environ.get('C360_JWT_SIGNING_KEY', SECRET_KEY),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# Per-scope throttles for the OTP endpoints so codes can't be brute-forced.
REST_FRAMEWORK.setdefault('DEFAULT_THROTTLE_CLASSES', ['rest_framework.throttling.ScopedRateThrottle'])
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
    'otp_request': os.environ.get('C360_OTP_REQUEST_RATE', '20/hour'),
    'otp_verify': os.environ.get('C360_OTP_VERIFY_RATE', '10/hour'),
    'login': os.environ.get('C360_LOGIN_RATE', '30/hour'),
}

# ---------------------------------------------------------------------------
# Email — used to deliver OTP / password-reset codes. Dev uses the console backend
# (mail is printed to the server log); point EMAIL_* at SMTP for real delivery.
# ---------------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get('C360_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587') or '587')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'HFCB Customer 360 <no-reply@hfcb.co.ke>')
APP_BRAND_NAME = 'HFCB Customer 360'

# Login 2FA: when on, sign-in is a two-step flow (password → emailed OTP). On by
# default; set C360_LOGIN_MFA=false to allow single-step login (e.g. for smoke tests).
C360_LOGIN_MFA = _env_bool('C360_LOGIN_MFA', True)

# ---------------------------------------------------------------------------
# CORS — the Next.js dev server talks to this API cross-origin.
# ---------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'C360_CORS_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000'
    ).split(',') if o.strip()
]
# The app is used on the office LAN, so the frontend is often opened via a machine
# IP (e.g. http://192.168.x.y:3000), not localhost. Allow localhost + private LAN
# ranges on any port so those origins aren't silently CORS-blocked (which looks like
# "stuck on login / can't load data"). Auth is a Bearer token, not a cookie, so this
# does not widen a credentialed surface.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^http://localhost:\d+$',
    r'^http://127\.0\.0\.1:\d+$',
    r'^http://192\.168\.\d{1,3}\.\d{1,3}:\d+$',
    r'^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d+$',
    r'^http://172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}:\d+$',
]
CORS_ALLOW_CREDENTIALS = True

# ---------------------------------------------------------------------------
# Session & CSRF — the SPA authenticates with a JWT Bearer token (see SIMPLE_JWT and
# c360/auth/claims.py), NOT a session cookie. These session/CSRF settings exist only
# for the Django admin and the DRF browsable API during local dev. Kept Lax + the
# secure flags below so that surface is safe when served over HTTPS in production.
# ---------------------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'C360_CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000'
    ).split(',') if o.strip()
]
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False   # the SPA reads this token and echoes it in a header
# In production over HTTPS, flip these on via env so cookies are TLS-only.
SESSION_COOKIE_SECURE = _env_bool('C360_COOKIE_SECURE', False)
CSRF_COOKIE_SECURE = _env_bool('C360_COOKIE_SECURE', False)
# Behind nginx/TLS the app sees plain HTTP; trust the proxy's X-Forwarded-Proto so
# Django knows the original request was HTTPS (correct scheme for CSRF origin checks
# and any secure-redirect logic). nginx sets this header (see deploy/nginx).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# When true (production), every data endpoint requires an authenticated session;
# only the auth + meta endpoints stay open (they mark themselves AllowAny). Left
# false in local dev so the documented header-driven RBAC seam still works.
if _env_bool('C360_REQUIRE_AUTH', False):
    REST_FRAMEWORK['DEFAULT_PERMISSION_CLASSES'] = [
        'rest_framework.permissions.IsAuthenticated',
    ]

# ---------------------------------------------------------------------------
# Customer 360 — data access configuration
# ---------------------------------------------------------------------------
# DATA_MODE selects the warehouse backend:
#   'mock' — clearly-labelled preview data, seeded in-process. No credentials
#            required. This is the default so the app runs end-to-end today.
#   'live' — the real Trino-backed repositories. Requires TRINO_* below and a
#            reachable warehouse. Flipping this value is the ONLY change needed
#            to move from preview to production data; no frontend change.
C360 = {
    'DATA_MODE': os.environ.get('C360_DATA_MODE', 'mock').strip().lower(),

    # trino_config — mirrors the shape the existing TrinoConnector expects.
    # Left unset in mock mode; supply via backend/.env for live mode.
    'trino_config': {
        'host': os.environ.get('TRINO_HOST', ''),
        'port': int(os.environ.get('TRINO_PORT', '443') or '443'),
        'user': os.environ.get('TRINO_USER', ''),
        'password': os.environ.get('TRINO_PASSWORD', ''),
        'http_scheme': os.environ.get('TRINO_HTTP_SCHEME', 'https'),
        # Core banking source-of-truth lives in the Trino lakehouse catalogue.
        'catalog': os.environ.get('TRINO_CATALOG', 'delta'),
        'schema': os.environ.get('TRINO_SCHEMA', 'gold_db'),
        # The internal Trino gateway (port 8443) uses a self-signed cert; disable
        # verification for LAN use. Never set false against a public endpoint.
        'verify': _env_bool('TRINO_VERIFY_SSL', False),
    },

    # The curated, report-ready customer/RM tables live in PostgreSQL, read by
    # the current reporting stack. Connection is env-driven and unused in mock.
    'postgres_config': {
        'host': os.environ.get('PG_HOST', ''),
        'port': int(os.environ.get('PG_PORT', '5432') or '5432'),
        'dbname': os.environ.get('PG_DBNAME', ''),
        'user': os.environ.get('PG_USER', ''),
        'password': os.environ.get('PG_PASSWORD', ''),
        # Optional libpq sslmode (disable/allow/prefer/require/verify-ca/verify-full).
        # Unset → libpq default ('prefer'). Set PG_SSLMODE=require if the warehouse's
        # pg_hba.conf only has hostssl rules for this user.
        'sslmode': os.environ.get('PG_SSLMODE', '').strip() or None,
    },
}
