# Generated by Django 5.2.16 on 2026-08-06 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.TextField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, choices=[('KISII BRANCH', 'KISII BRANCH'), ('NYERI BRANCH', 'NYERI BRANCH'), ('BURUBURU BRANCH', 'BURUBURU BRANCH'), ('NYALI BRANCH', 'NYALI BRANCH'), ('GILL HOUSE BRANCH', 'GILL HOUSE BRANCH'), ('NANYUKI BRANCH', 'NANYUKI BRANCH'), ('SAMEER BRANCH', 'SAMEER BRANCH'), ('NAKURU BRANCH', 'NAKURU BRANCH'), ('HEAD OFFICE BRANCH', 'HEAD OFFICE BRANCH'), ('MACHAKOS BRANCH', 'MACHAKOS BRANCH'), ('NAIVASHA BRANCH', 'NAIVASHA BRANCH'), ('KISUMU BRANCH', 'KISUMU BRANCH'), ('HURLINGHAM BRANCH', 'HURLINGHAM BRANCH'), ('TRM BRANCH', 'TRM BRANCH'), ('KITENGELA BRANCH', 'KITENGELA BRANCH'), ('ELDORET BRANCH', 'ELDORET BRANCH'), ('KENYATTA BRANCH', 'KENYATTA BRANCH'), ('REHANI BRANCH', 'REHANI BRANCH'), ('HF WHIZZ BRANCH', 'HF WHIZZ BRANCH'), ('MOMBASA BRANCH', 'MOMBASA BRANCH'), ('RIVERROAD BRANCH', 'RIVERROAD BRANCH'), ('EMBU BRANCH', 'EMBU BRANCH'), ('MERU BRANCH', 'MERU BRANCH'), ('THIKA BRANCH', 'THIKA BRANCH'), ('KOMAROCK BRANCH', 'KOMAROCK BRANCH'), ('WESTLANDS BRANCH', 'WESTLANDS BRANCH'), ('RONGAI BRANCH', 'RONGAI BRANCH')], max_length=32, null=True)),
                ('segment', models.CharField(blank=True, choices=[('FINANCIAL INSTITUTIONS', 'FINANCIAL INSTITUTIONS'), ('INSTITUTIONAL BANKING', 'INSTITUTIONAL BANKING'), ('INTERNAL ACCOUNTS', 'INTERNAL ACCOUNTS'), ('PB', 'PB'), ('SCHEME', 'SCHEME'), ('BUSINESS BANKING', 'BUSINESS BANKING'), ('COMMERCIAL', 'COMMERCIAL'), ('ULTIMATE', 'ULTIMATE'), ('PROJECT FINANCE', 'PROJECT FINANCE'), ('VIRTUAL', 'VIRTUAL'), ('STAFF', 'STAFF'), ('DIASPORA', 'DIASPORA'), ('unsegmented', 'unsegmented')], max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
