# Generated by Django 5.2.16 on 2026-08-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360', '0002_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(db_index=True, max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('product_name', models.CharField(blank=True, default='', max_length=120)),
                ('domain', models.CharField(default='HFCB', max_length=32)),
                ('score', models.FloatField(blank=True, null=True)),
                ('rule_id', models.CharField(blank=True, default='', max_length=32)),
                ('engine_version', models.CharField(blank=True, default='', max_length=32)),
                ('outcome', models.CharField(choices=[('pitched', 'Pitched — awaiting decision'), ('accepted', 'Accepted / taken up'), ('declined', 'Declined by customer'), ('not_relevant', 'Not relevant (model was off)')], default='pitched', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['cust_id', 'product'], name='c360_recomm_cust_id_39e2c3_idx'), models.Index(fields=['outcome'], name='c360_recomm_outcome_d147a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('cust_id', 'product', 'recorded_by'), name='uniq_feedback_cust_product_rm')],
            },
        ),
    ]
