# Generated by Django 5.2.16 on 2026-08-20 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360', '0003_recommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('days_behind', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'db_table': 'c360_health_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
    ]
