# Generated by Django 6.0.5 on 2026-09-09 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360', '0004_healthsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('kind', models.CharField(default='api', max_length=16)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('route', models.CharField(blank=True, default='', max_length=200)),
                ('path', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'c360_audit_event',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['-ts'], name='c360_audit__ts_636e0d_idx'), models.Index(fields=['user_id', '-ts'], name='c360_audit__user_id_75cee4_idx'), models.Index(fields=['kind', '-ts'], name='c360_audit__kind_c5bf53_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField(db_index=True)),
                ('instance', models.CharField(max_length=40)),
                ('count', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('client_errors', models.IntegerField(default=0)),
                ('sum_ms', models.BigIntegerField(default=0)),
                ('p50_ms', models.IntegerField(default=0)),
                ('p95_ms', models.IntegerField(default=0)),
                ('p99_ms', models.IntegerField(default=0)),
                ('max_ms', models.IntegerField(default=0)),
                ('by_status', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'c360_metric_minute',
                'ordering': ['-minute'],
                'indexes': [models.Index(fields=['-minute'], name='c360_metric_minute_ae6327_idx')],
                'constraints': [models.UniqueConstraint(fields=('minute', 'instance'), name='uniq_metric_minute_instance')],
            },
        ),
    ]
