# Generated by Django 5.2.16 on 2026-09-10 08:56

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('c360', '0005_auditevent_metricminute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sales_code', models.TextField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, choices=[('KISII BRANCH', 'KISII BRANCH'), ('NYERI BRANCH', 'NYERI BRANCH'), ('BURUBURU BRANCH', 'BURUBURU BRANCH'), ('NYALI BRANCH', 'NYALI BRANCH'), ('GILL HOUSE BRANCH', 'GILL HOUSE BRANCH'), ('NANYUKI BRANCH', 'NANYUKI BRANCH'), ('SAMEER BRANCH', 'SAMEER BRANCH'), ('NAKURU BRANCH', 'NAKURU BRANCH'), ('HEAD OFFICE BRANCH', 'HEAD OFFICE BRANCH'), ('MACHAKOS BRANCH', 'MACHAKOS BRANCH'), ('NAIVASHA BRANCH', 'NAIVASHA BRANCH'), ('KISUMU BRANCH', 'KISUMU BRANCH'), ('HURLINGHAM BRANCH', 'HURLINGHAM BRANCH'), ('TRM BRANCH', 'TRM BRANCH'), ('KITENGELA BRANCH', 'KITENGELA BRANCH'), ('ELDORET BRANCH', 'ELDORET BRANCH'), ('KENYATTA BRANCH', 'KENYATTA BRANCH'), ('REHANI BRANCH', 'REHANI BRANCH'), ('HF WHIZZ BRANCH', 'HF WHIZZ BRANCH'), ('MOMBASA BRANCH', 'MOMBASA BRANCH'), ('RIVERROAD BRANCH', 'RIVERROAD BRANCH'), ('EMBU BRANCH', 'EMBU BRANCH'), ('MERU BRANCH', 'MERU BRANCH'), ('THIKA BRANCH', 'THIKA BRANCH'), ('KOMAROCK BRANCH', 'KOMAROCK BRANCH'), ('WESTLANDS BRANCH', 'WESTLANDS BRANCH'), ('RONGAI BRANCH', 'RONGAI BRANCH')], max_length=32, null=True)),
                ('segment', models.CharField(blank=True, choices=[('FINANCIAL INSTITUTIONS', 'FINANCIAL INSTITUTIONS'), ('INSTITUTIONAL BANKING', 'INSTITUTIONAL BANKING'), ('INTERNAL ACCOUNTS', 'INTERNAL ACCOUNTS'), ('PB', 'PB'), ('SCHEME', 'SCHEME'), ('BUSINESS BANKING', 'BUSINESS BANKING'), ('COMMERCIAL', 'COMMERCIAL'), ('ULTIMATE', 'ULTIMATE'), ('PROJECT FINANCE', 'PROJECT FINANCE'), ('VIRTUAL', 'VIRTUAL'), ('STAFF', 'STAFF'), ('DIASPORA', 'DIASPORA'), ('unsegmented', 'unsegmented')], max_length=32, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical profile',
                'verbose_name_plural': 'historical profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecommendationFeedback',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cust_id', models.CharField(db_index=True, max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('product_name', models.CharField(blank=True, default='', max_length=120)),
                ('domain', models.CharField(default='HFCB', max_length=32)),
                ('score', models.FloatField(blank=True, null=True)),
                ('rule_id', models.CharField(blank=True, default='', max_length=32)),
                ('engine_version', models.CharField(blank=True, default='', max_length=32)),
                ('outcome', models.CharField(choices=[('pitched', 'Pitched — awaiting decision'), ('accepted', 'Accepted / taken up'), ('declined', 'Declined by customer'), ('not_relevant', 'Not relevant (model was off)')], default='pitched', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recommendation feedback',
                'verbose_name_plural': 'historical recommendation feedbacks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'db_table': 'c360_historical_user',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUser_groups',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='c360.historicaluser')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HistoricalUser_groups',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
