# Generated by Django 5.2.16 on 2026-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360', '0006_historicalprofile_historicalrecommendationfeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('firing', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, default='', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notify_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'c360_alert_state',
                'ordering': ['key'],
            },
        ),
    ]
