# Generated by Django 5.2.16 on 2026-09-11 05:17

from django.conf import settings
from django.db import migrations, models


def backfill_usernames(apps, schema_editor):
    """Copy the linked account's username onto existing rows.

    Rows written before this migration carry only the foreign key. The new
    uniqueness rule is keyed on the username, so without this every pre-existing
    row would hold '' and two different RMs' marks on the same customer+product
    would collide the moment the constraint is added.
    """
    Feedback = apps.get_model('c360', 'RecommendationFeedback')
    for row in Feedback.objects.filter(recorded_by__isnull=False).select_related('recorded_by'):
        Feedback.objects.filter(pk=row.pk).update(recorded_by_username=row.recorded_by.username)


def noop(apps, schema_editor):
    """Reversing drops the column anyway, so there is nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('c360', '0007_alertstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recommendationfeedback',
            name='uniq_feedback_cust_product_rm',
        ),
        migrations.AddField(
            model_name='historicalrecommendationfeedback',
            name='recorded_by_username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='recorded_by_username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.RunPython(backfill_usernames, noop),
        migrations.AddConstraint(
            model_name='recommendationfeedback',
            constraint=models.UniqueConstraint(fields=('cust_id', 'product', 'recorded_by_username'), name='uniq_feedback_cust_product_rm'),
        ),
    ]
