# Generated by Django 5.2.16 on 2026-09-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360', '0008_feedback_actor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'c360_app_heartbeat',
                'ordering': ['-minute'],
                'indexes': [models.Index(fields=['-minute'], name='c360_app_he_minute_93e869_idx')],
            },
        ),
    ]
