# Generated by Django 6.0.5 on 2026-10-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c360', '0009_app_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecommendationfeedback',
            name='outcome',
            field=models.CharField(choices=[('pitched', 'Pitched, awaiting decision'), ('accepted', 'Accepted / taken up'), ('declined', 'Declined by customer'), ('not_relevant', 'Not relevant (model was off)')], default='pitched', max_length=16),
        ),
        migrations.AlterField(
            model_name='recommendationfeedback',
            name='outcome',
            field=models.CharField(choices=[('pitched', 'Pitched, awaiting decision'), ('accepted', 'Accepted / taken up'), ('declined', 'Declined by customer'), ('not_relevant', 'Not relevant (model was off)')], default='pitched', max_length=16),
        ),
    ]
